apiVersion: v1
kind: Service
metadata:
  name: real-time
spec:
  selector:
    app.kubernetes.io/name: "real-time"
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8080
