apiVersion: v1
kind: Service
metadata:
  name: leaderboard
spec:
  selector:
    app.kubernetes.io/name: "leaderboard"
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8082
