apiVersion: apps/v1
kind: Deployment
metadata:
  name: "session-{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "session"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/part-of: "tryit"
    app.kubernetes.io/env: "{{ .Values.environment | default "prod" }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  revisionHistoryLimit: 12
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "session"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "session"
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
    spec:
      initContainers:
      - name: wait-for-rabbitmq
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z {{ .Values.env.RABBITMQ_HOST }} {{ .Values.env.RABBITMQ_PORT }}; do echo "Waiting for RabbitMQ to be ready..."; sleep 2; done; echo "RabbitMQ is ready."']
      - name: wait-for-redis
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z {{ .Values.env.REDIS_HOST }} {{ .Values.env.REDIS_PORT }}; do echo "Waiting for Redis to be ready..."; sleep 2; done; echo "Redis is ready."']
      containers:
      - name: "session"
        image: "{{ .Values.image.name }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        env:
          - name: RABBITMQ_USER
            value: "{{ .Values.env.RABBITMQ_USER }}"
          - name: RABBITMQ_PASSWORD
            value: "{{ .Values.env.RABBITMQ_PASSWORD }}"
          - name: RABBITMQ_HOST
            value: "{{ .Values.env.RABBITMQ_HOST }}"
          - name: RABBITMQ_PORT
            value: "{{ .Values.env.RABBITMQ_PORT }}"
          - name: REDIS_HOST
            value: "{{ .Values.env.REDIS_HOST }}"
          - name: REDIS_PORT
            value: "{{ .Values.env.REDIS_PORT }}"
          - name: REALTIME_SERVICE_HOST
            value: "{{ .Values.env.REALTIME_SERVICE_HOST }}"
          - name: REALTIME_SERVICE_PORT
            value: "{{ .Values.env.REALTIME_SERVICE_PORT }}"
          - name: SESSION_SERVICE_HOST
            value: "{{ .Values.env.SESSION_SERVICE_HOST }}"
          - name: SESSION_SERVICE_PORT
            value: "{{ .Values.env.SESSION_SERVICE_PORT }}"
          - name: JWT_SECRET_KEY
            value: "{{ .Values.env.JWT_SECRET_KEY }}"
          - name: ENV
            value: "{{ .Values.env.ENV }}"
        ports:
        - name: http
          containerPort: 8081
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
